networks:
  snake:

services:
  backend:
    build: ./backend
    networks:
      - snake
    ports:
      - "5000:5000"

  redis:
    image: redis
    networks:
      - snake
    ports:
      - "6379:6379"